# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: CV
    url: uploads/CV_Dijun.pdf
    weight: 30
  - name: Teaching
    url: '#teaching'
    weight: 40
  - name: Data & Code
    url:  '#data-code'
    weight: 50
  - name: References
    url: '#references'
    weight: 60
  - name: Projects
    url: '#projects'
    weight: 70
  
